pipelines:  
  - name: automation_demo_PDE
    steps:  
      - name: demoZstepAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        type: Bash
        execution:
          onExecute: 
            - echo "HELLO WORLD"
          onFailure:
            - echo "on fail success"
          onSuccess:
            - echo "on Success verify onCommit autoTrigger RUN:3"
          onComplete:
            - echo "on complete"
